version: '3'

services:

  dockertest1118_nginx:    # 修改这里
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dockertest1118_app    # 修改这里
    restart: always

  dockertest1118_app:    # 修改这里
    build: . 
    ports:
      - ":::3000:3000"
    environment:
      - DB_HOST=dockertest1118_db    # 修改这里
      - DB_USER=root
      - DB_PASSWORD=77447744dcl
      - DB_NAME=testdb
    depends_on:
      - dockertest1118_db    # 修改这里
    restart: always

  dockertest1118_db:    # 修改这里
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
      - "127.0.0.1:33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=77447744dcl
      - MYSQL_DATABASE=testdb
    volumes:
      - dockertest1118_data:/var/lib/mysql    # 修改这里
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql  # 添加
    restart: always

volumes:
  dockertest1118_data:    # 修改这里
